/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface DemoEventEmitter {
    }
    interface DemoPassingProps {
        "action": Function;
        "text": string;
    }
    interface DemoRichProps {
        "list": Array<string>;
    }
}
export interface DemoEventEmitterCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLDemoEventEmitterElement;
}
declare global {
    interface HTMLDemoEventEmitterElement extends Components.DemoEventEmitter, HTMLStencilElement {
    }
    var HTMLDemoEventEmitterElement: {
        prototype: HTMLDemoEventEmitterElement;
        new (): HTMLDemoEventEmitterElement;
    };
    interface HTMLDemoPassingPropsElement extends Components.DemoPassingProps, HTMLStencilElement {
    }
    var HTMLDemoPassingPropsElement: {
        prototype: HTMLDemoPassingPropsElement;
        new (): HTMLDemoPassingPropsElement;
    };
    interface HTMLDemoRichPropsElement extends Components.DemoRichProps, HTMLStencilElement {
    }
    var HTMLDemoRichPropsElement: {
        prototype: HTMLDemoRichPropsElement;
        new (): HTMLDemoRichPropsElement;
    };
    interface HTMLElementTagNameMap {
        "demo-event-emitter": HTMLDemoEventEmitterElement;
        "demo-passing-props": HTMLDemoPassingPropsElement;
        "demo-rich-props": HTMLDemoRichPropsElement;
    }
}
declare namespace LocalJSX {
    interface DemoEventEmitter {
        "onDemoEvent"?: (event: DemoEventEmitterCustomEvent<any>) => void;
    }
    interface DemoPassingProps {
        "action"?: Function;
        "text"?: string;
    }
    interface DemoRichProps {
        "list"?: Array<string>;
    }
    interface IntrinsicElements {
        "demo-event-emitter": DemoEventEmitter;
        "demo-passing-props": DemoPassingProps;
        "demo-rich-props": DemoRichProps;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "demo-event-emitter": LocalJSX.DemoEventEmitter & JSXBase.HTMLAttributes<HTMLDemoEventEmitterElement>;
            "demo-passing-props": LocalJSX.DemoPassingProps & JSXBase.HTMLAttributes<HTMLDemoPassingPropsElement>;
            "demo-rich-props": LocalJSX.DemoRichProps & JSXBase.HTMLAttributes<HTMLDemoRichPropsElement>;
        }
    }
}
